baseURL = "https://cooking.amine-rahmane.fr/"
languageCode = "fr-FR"
title = "Amine's cooking"
theme = "smol"

# Parameters
[params]
    subtitle = "Hello there"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/dasporal"
        weight = 1 

    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/dasporal"
        weight = 2 

    [[menu.footer]]
        name = "Imprint"
        url = "/imprint"
        weight = 3 

[taxonomies]
  category = "categories"
  tag = "tags"        